apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |-
      - op: replace
        path: /spec/triggers/0/template/http/url
        value: http://daniel-cf-url.ngrok.io/2.0/api/events
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Sensor
